HW15 is completed
AlekseyPorandaykin/otus_hw_go pull request #15
Opened 2023-02-19 20:54 UTC by AlekseyPorandaykin

## Домашнее задание №15 «Докеризация и интеграционное тестирование Календаря»

### Критерии оценки
- [ ] Проект полностью запускается и останавливается с помощью `make up` / `make down` - 3 балла
- [ ] Интеграционные тесты запускаются с помощью `make integration-tests`. Команда возвращает верный код ответа - 1 балл

Интеграционные тесты покрывают бизнес сценарии:
- [ ] добавление события и обработка бизнес ошибок - 2 балла
- [ ] получение листинга событий на день/неделю/месяц - 2 балла
- [ ] отправка уведомлений - 2 балла

#### Зачёт от 7 баллов

2023-02-19 20:55 UTC, AlekseyPorandaykin commented
Результат вывода команды `make integration-tests`

![image](https://user-images.githubusercontent.com/10035142/219974642-dd109fd0-5628-4fe0-84f8-f7bdc06ed3d3.png)

2023-02-20 04:31 UTC, dshemin requested changes

2023-02-20 04:31 UTC, dshemin commented on hw12_13_14_15_calendar/Makefile
> +	docker-compose --file=$(DOCKER_COMPOSE_FILE) --env-file $(DOCKER_ENV_FILE) build --no-cache pgs rabbitmq
Важно:

Не самы лучший способ. Лучше описать docker-compose файл так, чтобы его можно было запустить одной командой. Посмотрите на данныую статью https://www.howtogeek.com/devops/how-to-make-docker-compose-wait-for-dependency-containers/

2023-02-20 04:31 UTC, dshemin commented on hw12_13_14_15_calendar/tests/features/events.feature
> +  Scenario: Get events on week
Важно:

Тест продублирован

2023-02-20 04:31 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	_, err := s.db.ExecContext(ctx, saveLogQuery, eventID, body, date)
Важно:

Если не добавляете контекста к ошибке, то лучше просто:

```
_, err := ...
return err
```

2023-02-27 06:50 UTC, dshemin approved these changes

2023-03-01 21:11 UTC, merged