HW4 is completed
AlekseyPorandaykin/otus_hw_go pull request #4
Opened 2022-01-23 23:07 UTC by AlekseyPorandaykin

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-01-25 16:10 UTC, agneum requested changes
Спасибо за вариант решения. 
Хорошая работа, однако есть ряд существенных замечаний, поэтому возвращаю задание на доработку
Итого: 6 баллов из 10

2022-01-25 16:10 UTC, agneum commented on hw04_lru_cache/cache.go
> +		}
По условию задания
> Сложность операций Set/Get должна быть O(1)

В этом поможет структура `cacheItem`, которая была удалена

2022-01-25 16:10 UTC, agneum commented on hw04_lru_cache/list.go
> +	list.linkValues(list.Back(), nextValue)
А если в списке нет элементов?

2022-01-25 16:10 UTC, agneum commented on hw04_lru_cache/list.go
> +		if item.Prev != nil {
Как такое может быть, что элемент первый в списке, и его предыдущий элемент не пустой?

2022-01-25 16:10 UTC, agneum commented on hw04_lru_cache/list.go
> +
А если удаляем последний элемент списка?

2022-01-25 16:10 UTC, agneum commented on hw04_lru_cache/list.go
> +func (list *list) linkValues(prevValue, nextValue *ListItem) {
Субъективно, может быть сложно постоянно держать в голове логику связки элементов. 
Предложил бы использовать её в явном виде, тем более она упростится для большинства конкретных случаев

2022-01-25 16:10 UTC, agneum commented on hw04_lru_cache/list.go
> +}
Не хватает новых тестов для списка

2022-02-17 21:14 UTC, AlekseyPorandaykin commented on hw04_lru_cache/list.go
> +func (list *list) linkValues(prevValue, nextValue *ListItem) {
При связывании элементов логика дублируется, поэтому я вынес её в приватный метод. 
linkValues - просто связывает два элемента,  и не важно откуда он вызывается: добавить в конец, добавить в начало или удалить элемент из списка

2022-02-21 12:36 UTC, agneum approved these changes
Спасибо за правки, выглядит хорошо.
Осталось поправить замечание линтера, чтобы смержить PR
10/10

2022-02-21 12:36 UTC, agneum commented on hw04_lru_cache/cache.go
> +	_, itemExist := cache.items[item.key]
Можно использовать `key` вместо обращения к полю структуры `item.key` - они одинаковы

2022-02-21 12:36 UTC, agneum commented on hw04_lru_cache/list_test.go
> +		require.True(t, l.Back() == penultimateItem, "When the last value is removed, the last element is set to the penultimate one.")
Слишком длинная строка - нужно поправить, иначе пайплайн не пройдёт успешно и не позволит смержить

2022-02-21 20:01 UTC, merged

2022-03-23 23:11 UTC, AlekseyPorandaykin commented
done